const PROFILE_KEY="classmate-profile-v3";let profile=JSON.parse(localStorage.getItem(PROFILE_KEY)||"null"),attendance={},picked=null,anchor=new Date();const $=id=>document.getElementById(id);
const key=()=>`classmate-attendance-v3-S${profile.section}`;const classes=()=>TIMETABLE.filter(c=>c.section===String(profile.section));const save=()=>localStorage.setItem(key(),JSON.stringify(attendance));const load=()=>attendance=JSON.parse(localStorage.getItem(key())||"{}");
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}function parseDate(s){let[y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)}function fmt(d){return new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(d)}
document.querySelectorAll("#sectionPicker button").forEach(b=>b.onclick=()=>{picked=b.dataset.s;document.querySelectorAll("#sectionPicker button").forEach(x=>x.classList.toggle("selected",x===b))});
$("startBtn").onclick=()=>{let n=$("nameInput").value.trim();if(!n||!picked)return toast("Enter your name and choose a section");profile={name:n,section:picked};localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));load();$("setup").classList.add("hidden");renderAll()};
function boot(){if(!profile){$("setup").classList.remove("hidden");return}load();renderAll()}
function renderAll(){let h=new Date().getHours(),g=h<12?"Good morning":h<17?"Good afternoon":"Good evening";$("greeting").textContent=`${g}, ${profile.name} 👋`;$("currentDate").textContent=fmt(new Date());$("profileLine").textContent=`Section ${profile.section} · Term I`;renderToday();renderAttendance();renderWeek();initFilters();renderPast();updateOverall()}
function classCard(c){let s=attendance[c.id];return `<article class="class-card"><div class="time"><strong>${c.start}</strong><span>to ${c.end}</span></div><div class="class-info"><span class="code">${c.code}</span><h3>${c.name}</h3><p>${c.room}</p></div><div class="actions"><button class="action present ${s==="present"?"selected":""}" onclick="mark('${c.id}','present')">✓ Present</button><button class="action absent ${s==="absent"?"selected":""}" onclick="mark('${c.id}','absent')">✕ Absent</button></div></article>`}
function renderToday(){let cs=classes().filter(c=>c.date===localDate()),ev=SPECIAL_EVENTS.filter(e=>e.date===localDate());$("todayCount").textContent=`${cs.length} ${cs.length===1?"class":"classes"}`;$("todayList").innerHTML=cs.length?cs.map(classCard).join(""):`<div class="empty"><strong>A quiet day in the hills 🌿</strong><span>${ev.map(e=>e.title).join(" · ")||"No classes scheduled today."}</span></div>`}
function mark(id,status){attendance[id]=attendance[id]===status?undefined:status;if(!attendance[id])delete attendance[id];save();renderToday();renderAttendance();renderPast();updateOverall();toast(status==="present"?"Marked present ✓":"Marked absent")}
function stats(code){let m=classes().filter(c=>c.code===code&&attendance[c.id]),p=m.filter(c=>attendance[c.id]==="present").length;return{p,t:m.length,pct:m.length?p/m.length*100:null}}
function advice(p,t){if(!t)return{text:"Mark a class to begin tracking.",type:"watch"};let x=p/t*100;if(x>=75){let n=0;while(p/(t+n+1)*100>=75)n++;return n?{text:`You can miss ${n} more ${n===1?"class":"classes"} and remain at or above 75%.`,type:x>=85?"safe":"watch"}:{text:"At the 75% line — attend the next class to create a buffer.",type:"watch"}}let n=0;while((p+n)/(t+n)*100<75)n++;return{text:`Attend the next ${n} ${n===1?"class":"classes"} consecutively to reach 75%.`,type:"risk"}}
function renderAttendance(){$("attendanceGrid").innerHTML=Object.keys({ME:1,FRA:1,DMV:1,MM:1,SDM:1,SGD:1,"S&B":1}).map(code=>{let s=stats(code),a=advice(s.p,s.t);return `<article class="attendance-card"><div class="attendance-top"><div><span class="code">${code}</span><h3>${classes().find(c=>c.code===code)?.name||code}</h3></div><div class="pct">${s.pct===null?"—":s.pct.toFixed(1)+"%"}</div></div><div class="progress"><div class="bar" style="width:${s.pct||0}%"></div></div><div class="meta"><span>${s.p} attended</span><span>${s.t} classes marked</span></div><div class="advice ${a.type}">${a.text}</div></article>`}).join("")}
function updateOverall(){let m=classes().filter(c=>attendance[c.id]),p=m.filter(c=>attendance[c.id]==="present").length;$("overall").textContent=m.length?(p/m.length*100).toFixed(1)+"%":"—";$("overallDetail").textContent=m.length?`${p} of ${m.length} marked classes attended`:"No classes marked yet"}
function monday(d){let x=new Date(d),day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));x.setHours(0,0,0,0);return x}
function renderWeek(){let mon=monday(anchor),sun=new Date(mon);sun.setDate(mon.getDate()+6);$("weekLabel").textContent=`${mon.toLocaleDateString("en-IN",{day:"numeric",month:"short"})} – ${sun.toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}`;let html="";for(let i=0;i<7;i++){let d=new Date(mon);d.setDate(mon.getDate()+i);let k=localDate(d),cs=classes().filter(c=>c.date===k),ev=SPECIAL_EVENTS.filter(e=>e.date===k);html+=`<article class="day ${k===localDate()?"today":""}"><div class="day-head"><span>${d.toLocaleDateString("en-IN",{weekday:"short"})}</span><strong>${d.getDate()} ${d.toLocaleDateString("en-IN",{month:"short"})}</strong></div>${cs.map(c=>`<div class="mini"><strong>${c.code}</strong><span>${c.start} – ${c.end}</span></div>`).join("")}${ev.map(e=>`<div class="event">${e.title}</div>`).join("")}</article>`}$("weekGrid").innerHTML=html;$("scheduleDate").value=localDate(anchor)}
$("prevWeek").onclick=()=>{anchor.setDate(anchor.getDate()-7);renderWeek()};$("nextWeek").onclick=()=>{anchor.setDate(anchor.getDate()+7);renderWeek()};$("scheduleDate").onchange=e=>{if(e.target.value)anchor=parseDate(e.target.value);renderWeek()};
function initFilters(){if(!$("fromDate").value){let all=classes(),first=all[0]?.date||localDate();$("fromDate").value=first;$("toDate").value=localDate();$("subjectFilter").innerHTML='<option value="ALL">All subjects</option>'+Object.keys({ME:1,FRA:1,DMV:1,MM:1,SDM:1,SGD:1,"S&B":1}).map(x=>`<option value="${x}">${x}</option>`).join("")}}
function renderPast(){let from=$("fromDate").value,to=$("toDate").value,sub=$("subjectFilter").value,st=$("statusFilter").value,today=localDate();let list=classes().filter(c=>c.date<=today&&(!from||c.date>=from)&&(!to||c.date<=to)&&(sub==="ALL"||c.code===sub)&&(st==="ALL"||(st==="unmarked"&&!attendance[c.id])||attendance[c.id]===st)).sort((a,b)=>b.date.localeCompare(a.date)||a.start.localeCompare(b.start));let groups={};list.forEach(c=>(groups[c.date]??=[]).push(c));$("pastList").innerHTML=Object.keys(groups).length?Object.entries(groups).map(([date,cs])=>`<article class="past-day"><div class="past-head">${fmt(parseDate(date))}${date===today?" · Today":""}</div>${cs.map(c=>`<div class="past-row"><div><strong>${c.start}</strong><br><small>${c.end}</small></div><div><span class="code">${c.code}</span><strong style="display:block;margin-top:3px">${c.name}</strong></div><div class="actions"><button class="action present ${attendance[c.id]==="present"?"selected":""}" onclick="mark('${c.id}','present')">✓ Present</button><button class="action absent ${attendance[c.id]==="absent"?"selected":""}" onclick="mark('${c.id}','absent')">✕ Absent</button></div></div>`).join("")}</article>`).join(""):`<div class="empty"><strong>Nothing here 🌱</strong><span>No classes match these filters.</span></div>`}
["fromDate","toDate","subjectFilter","statusFilter"].forEach(id=>$(id).onchange=renderPast);$("resetFilters").onclick=()=>{$("fromDate").value=classes()[0]?.date||localDate();$("toDate").value=localDate();$("subjectFilter").value="ALL";$("statusFilter").value="ALL";renderPast()};
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));t.classList.add("active");$(`${t.dataset.view}View`).classList.add("active");if(t.dataset.view==="mark")renderPast()});
$("settingsBtn").onclick=()=>{$("settingsName").value=profile.name;$("settingsSection").value=profile.section;$("settings").classList.remove("hidden")};$("closeSettings").onclick=()=>$("settings").classList.add("hidden");$("saveSettings").onclick=()=>{let n=$("settingsName").value.trim(),s=$("settingsSection").value;if(!n)return toast("Enter your name");profile={name:n,section:s};localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));load();$("settings").classList.add("hidden");$("fromDate").value="";renderAll();toast("Profile updated")};$("clearData").onclick=()=>{if(confirm("Delete attendance saved for this section on this device?")){attendance={};save();$("settings").classList.add("hidden");renderAll();toast("Attendance deleted")}};
function toast(m){let t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1600)}if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));boot();